from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from django.utils import timezone
from django.db.models import Q, Sum, Avg
from django.http import HttpResponse
import csv
import datetime
from .models import (
    Repair, Attachment, Inspection, InspectionEntry, 
    TreatmentLog, TreatmentParameter, Incident, User,
    Exhauster, License, SludgeCollection
)
from .serializers import (
    RepairSerializer, AttachmentSerializer, InspectionSerializer,
    TreatmentLogSerializer, IncidentSerializer, UserSerializer,
    ExhausterSerializer, LicenseSerializer, SludgeCollectionSerializer
)
from .permissions import IsSupervisor, IsInspector, IsOperator


# --- MONTHLY SUMMARY VIEW WITH CSV EXPORT ---

class MonthlySummaryView(APIView):
    """
    API endpoint for monthly dashboard summary with CSV export capability.
    
    Endpoints:
    - GET /api/summaries/monthly/?year=2024&month=3 - Get JSON summary
    - GET /api/summaries/monthly/?year=2024&month=3&export=csv - Download CSV report
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        now = datetime.datetime.now()
        try:
            year = int(request.query_params.get('year', now.year))
            month = int(request.query_params.get('month', now.month))
        except ValueError:
            year, month = now.year, now.month

        # Define date range for the specified month
        start_date = datetime.date(year, month, 1)
        if month == 12:
            end_date = datetime.date(year + 1, 1, 1) - datetime.timedelta(days=1)
        else:
            end_date = datetime.date(year, month + 1, 1) - datetime.timedelta(days=1)

        # --- DATA AGGREGATION QUERIES ---
        
        # Collection System Data
        incidents = Incident.objects.filter(
            reported_at__date__gte=start_date,
            reported_at__date__lte=end_date
        )
        
        repairs = Repair.objects.filter(
            created_at__date__gte=start_date,
            created_at__date__lte=end_date
        )
        
        # Sludge Management Data
        sludge_collections = SludgeCollection.objects.filter(
            collection_date__gte=start_date,
            collection_date__lte=end_date,
            manifest_status='completed'
        )
        
        total_sludge = sludge_collections.aggregate(Sum('volume_m3'))['volume_m3__sum'] or 0
        
        # Sludge by source type
        res_sludge = sludge_collections.filter(source_type='residential').aggregate(Sum('volume_m3'))['volume_m3__sum'] or 0
        inst_sludge = sludge_collections.filter(source_type='institutional').aggregate(Sum('volume_m3'))['volume_m3__sum'] or 0
        comm_sludge = sludge_collections.filter(source_type__in=['commercial', 'industrial']).aggregate(Sum('volume_m3'))['volume_m3__sum'] or 0
        
        # Treatment Plant Performance
        treatment_logs = TreatmentLog.objects.filter(
            report_date__gte=start_date,
            report_date__lte=end_date
        )
        
        # Calculate average BOD removal for the period
        bod_params = TreatmentParameter.objects.filter(
            tlog__in=treatment_logs,
            parameter__iexact='bod'
        ).exclude(influent_value__isnull=True).exclude(effluent_value__isnull=True)
        
        total_removal = 0
        count = 0
        for param in bod_params:
            if param.influent_value > 0:  # Avoid division by zero
                removal = ((param.influent_value - param.effluent_value) / param.influent_value) * 100
                total_removal += removal
                count += 1
        
        avg_bod_removal = total_removal / count if count > 0 else 0

        # Determine if the user wants a CSV
        export_format = request.query_params.get('export', 'json').lower()

        if export_format == 'csv':
            # Create the HttpResponse object with the appropriate CSV header.
            response = HttpResponse(
                content_type='text/csv',
                headers={'Content-Disposition': f'attachment; filename="KICOWASCO_Summary_{year}_{month:02d}.csv"'},
            )
            
            writer = csv.writer(response)
            
            # Write CSV header and data
            writer.writerow(['KICOWASCO Monthly Summary Report'])
            writer.writerow(['Period', f'{year}-{month:02d}'])
            writer.writerow(['Generated On', now.strftime('%Y-%m-%d %H:%M:%S')])
            writer.writerow(['Generated By', request.user.get_full_name() or request.user.username])
            writer.writerow([])  # Blank row
            
            # Collection System
            writer.writerow(['--- COLLECTION SYSTEM ---'])
            writer.writerow(['Metric', 'Value'])
            writer.writerow(['Total Incidents Reported', incidents.count()])
            writer.writerow(['Resolved/Closed Incidents', incidents.filter(status__in=['resolved', 'closed']).count()])
            writer.writerow(['Pending Incidents', incidents.exclude(status__in=['resolved', 'closed']).count()])
            writer.writerow(['Repairs Completed', repairs.count()])
            
            # Incident breakdown by status
            for status_code, status_label in Incident.INCIDENT_STATUS:
                count = incidents.filter(status=status_code).count()
                if count > 0:
                    writer.writerow([f'Incidents - {status_label}', count])
            writer.writerow([])
            
            # Sludge Management
            writer.writerow(['--- SLUDGE MANAGEMENT ---'])
            writer.writerow(['Source Type', 'Volume (m³)'])
            writer.writerow(['Residential', round(res_sludge, 2)])
            writer.writerow(['Institutional', round(inst_sludge, 2)])
            writer.writerow(['Commercial/Industrial', round(comm_sludge, 2)])
            writer.writerow(['Total Sludge Collected', round(total_sludge, 2)])
            writer.writerow(['Number of Collections', sludge_collections.count()])
            if sludge_collections.count() > 0:
                writer.writerow(['Average Volume per Collection', round(total_sludge / sludge_collections.count(), 2)])
            writer.writerow([])
            
            # Treatment Plant
            writer.writerow(['--- TREATMENT PLANT PERFORMANCE ---'])
            writer.writerow(['Parameter', 'Value'])
            writer.writerow(['BOD Removal (%)', round(avg_bod_removal, 2)])
            writer.writerow(['Number of Treatment Logs', treatment_logs.count()])
            writer.writerow(['Logs with Alerts', treatment_logs.filter(alert=True).count()])
            if treatment_logs.count() > 0:
                writer.writerow(['Alert Percentage', round((treatment_logs.filter(alert=True).count() / treatment_logs.count() * 100), 2)])

            return response

        # Otherwise, return the standard JSON response for the React dashboard
        data = {
            "period": f"{year}-{month:02d}",
            "generated_at": now.isoformat(),
            "generated_by": {
                "id": request.user.id,
                "name": request.user.get_full_name() or request.user.username,
                "role": getattr(request.user, 'role', 'unknown')
            },
            "collection": {
                "total_incidents": incidents.count(),
                "resolved_incidents": incidents.filter(status__in=['resolved', 'closed']).count(),
                "pending_incidents": incidents.exclude(status__in=['resolved', 'closed']).count(),
                "repairs_completed": repairs.count(),
                "incident_breakdown": {
                    status: incidents.filter(status=status).count() 
                    for status, _ in Incident.INCIDENT_STATUS
                }
            },
            "sludge": {
                "total_volume_m3": round(total_sludge, 2),
                "total_collections": sludge_collections.count(),
                "breakdown": {
                    "residential": round(res_sludge, 2),
                    "institutional": round(inst_sludge, 2),
                    "commercial": round(comm_sludge, 2)
                },
                "average_volume_per_collection": round(total_sludge / sludge_collections.count(), 2) if sludge_collections.count() > 0 else 0
            },
            "treatment": {
                "avg_bod_removal_percent": round(avg_bod_removal, 2),
                "total_logs": treatment_logs.count(),
                "logs_with_alerts": treatment_logs.filter(alert=True).count(),
                "alert_percentage": round((treatment_logs.filter(alert=True).count() / treatment_logs.count() * 100) if treatment_logs.count() > 0 else 0, 2)
            }
        }
        return Response(data)


# --- EXHAUSTER MANAGEMENT VIEWSETS ---

class ExhausterViewSet(viewsets.ModelViewSet):
    """
    ViewSet for Viewing and Editing the Exhauster Registry.
    """
    queryset = Exhauster.objects.all().order_by('-date_registered', 'reg_no')
    serializer_class = ExhausterSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter exhausters based on query parameters"""
        queryset = super().get_queryset()
        
        # Filter by status
        status = self.request.query_params.get('status', None)
        if status:
            queryset = queryset.filter(status=status)
        
        # Filter by registration number (partial match)
        reg_no = self.request.query_params.get('reg_no', None)
        if reg_no:
            queryset = queryset.filter(reg_no__icontains=reg_no)
        
        # Filter by owner (partial match)
        owner = self.request.query_params.get('owner', None)
        if owner:
            queryset = queryset.filter(owner__icontains=owner)
            
        return queryset

    @action(detail=False, methods=['get'])
    def active(self, request):
        """Get only active exhausters"""
        active_exhausters = self.get_queryset().filter(status='active')
        serializer = self.get_serializer(active_exhausters, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['get'])
    def licenses(self, request, pk=None):
        """Get all licenses for a specific exhauster"""
        exhauster = self.get_object()
        licenses = exhauster.licenses.all().order_by('-end_date')
        serializer = LicenseSerializer(licenses, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['get'])
    def collections(self, request, pk=None):
        """Get all sludge collections for a specific exhauster"""
        exhauster = self.get_object()
        collections = exhauster.collections.all().order_by('-collection_date')
        serializer = SludgeCollectionSerializer(collections, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def summary(self, request):
        """Get summary statistics for exhausters"""
        queryset = self.get_queryset()
        total = queryset.count()
        active = queryset.filter(status='active').count()
        inactive = queryset.filter(status='inactive').count()
        suspended = queryset.filter(status='suspended').count()
        
        return Response({
            'total': total,
            'active': active,
            'inactive': inactive,
            'suspended': suspended,
            'active_percentage': round((active / total * 100) if total > 0 else 0, 2)
        })


class LicenseViewSet(viewsets.ModelViewSet):
    """
    ViewSet for Managing Exhauster Operating Licenses.
    """
    queryset = License.objects.all().order_by('-start_date')
    serializer_class = LicenseSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter licenses based on query parameters"""
        queryset = super().get_queryset()
        
        # Filter by status
        status = self.request.query_params.get('status', None)
        if status:
            queryset = queryset.filter(status=status)
        
        # Filter by exhauster
        exhauster_id = self.request.query_params.get('exhauster_id', None)
        if exhauster_id:
            queryset = queryset.filter(exhauster_id=exhauster_id)
        
        # Filter by date range
        from_date = self.request.query_params.get('from_date', None)
        to_date = self.request.query_params.get('to_date', None)
        
        if from_date:
            queryset = queryset.filter(start_date__gte=from_date)
        if to_date:
            queryset = queryset.filter(end_date__lte=to_date)
            
        return queryset

    @action(detail=False, methods=['get'])
    def valid(self, request):
        """Get currently valid licenses"""
        today = timezone.now().date()
        valid_licenses = self.get_queryset().filter(
            status='valid',
            start_date__lte=today,
            end_date__gte=today
        )
        serializer = self.get_serializer(valid_licenses, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def expiring(self, request):
        """Get licenses expiring within the next 30 days"""
        today = timezone.now().date()
        thirty_days = today + datetime.timedelta(days=30)
        
        expiring = self.get_queryset().filter(
            status='valid',
            end_date__gte=today,
            end_date__lte=thirty_days
        )
        serializer = self.get_serializer(expiring, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def expired(self, request):
        """Get expired licenses"""
        today = timezone.now().date()
        expired = self.get_queryset().filter(end_date__lt=today)
        serializer = self.get_serializer(expired, many=True)
        return Response(serializer.data)


class SludgeCollectionViewSet(viewsets.ModelViewSet):
    """
    ViewSet for the Sludge Manifest (Chain of Custody).
    """
    queryset = SludgeCollection.objects.all().order_by('-collection_date', '-created_at')
    serializer_class = SludgeCollectionSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter sludge collections based on query parameters"""
        queryset = super().get_queryset()
        user = self.request.user
        
        # Filter by driver if user is driver
        if user.role == 'driver':
            queryset = queryset.filter(exhauster_driver=user)
        
        # Filter by receiving officer if user is operator/supervisor
        if user.role in ['operator', 'supervisor'] and self.request.query_params.get('my_receipts'):
            queryset = queryset.filter(receiving_officer=user)
        
        # Filter by date range
        from_date = self.request.query_params.get('from_date', None)
        to_date = self.request.query_params.get('to_date', None)
        
        if from_date:
            queryset = queryset.filter(collection_date__gte=from_date)
        if to_date:
            queryset = queryset.filter(collection_date__lte=to_date)
        
        # Filter by source type
        source_type = self.request.query_params.get('source_type', None)
        if source_type:
            queryset = queryset.filter(source_type=source_type)
        
        # Filter by area/ward
        area_ward = self.request.query_params.get('area_ward', None)
        if area_ward:
            queryset = queryset.filter(area_ward__icontains=area_ward)
        
        # Filter by manifest status
        manifest_status = self.request.query_params.get('manifest_status', None)
        if manifest_status:
            queryset = queryset.filter(manifest_status=manifest_status)
        
        # Filter by exhauster
        exhauster_id = self.request.query_params.get('exhauster_id', None)
        if exhauster_id:
            queryset = queryset.filter(exhauster_id=exhauster_id)
            
        return queryset

    def perform_create(self, serializer):
        serializer.save(exhauster_driver=self.request.user)

    @action(detail=False, methods=['get'])
    def pending(self, request):
        """Get pending manifests (not yet completed)"""
        pending = self.get_queryset().filter(manifest_status='pending')
        serializer = self.get_serializer(pending, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def completed(self, request):
        """Get completed manifests"""
        completed = self.get_queryset().filter(manifest_status='completed')
        serializer = self.get_serializer(completed, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['post'])
    def complete(self, request, pk=None):
        """Mark a sludge collection manifest as completed with receiving officer notes"""
        collection = self.get_object()
        
        if collection.manifest_status == 'completed':
            return Response(
                {'error': 'This manifest is already completed'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        collection.receiving_officer = request.user
        collection.receiving_notes = request.data.get('receiving_notes', '')
        collection.manifest_status = 'completed'
        collection.save()
        
        serializer = self.get_serializer(collection)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def my_collections(self, request):
        """Get collections where current user was the driver"""
        collections = self.get_queryset().filter(exhauster_driver=request.user)
        serializer = self.get_serializer(collections, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def received_by_me(self, request):
        """Get collections received by current user"""
        collections = self.get_queryset().filter(receiving_officer=request.user)
        serializer = self.get_serializer(collections, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def summary(self, request):
        """Get summary statistics for sludge collections"""
        queryset = self.get_queryset()
        total = queryset.count()
        pending = queryset.filter(manifest_status='pending').count()
        completed = queryset.filter(manifest_status='completed').count()
        
        total_volume = queryset.aggregate(Sum('volume_m3'))['volume_m3__sum'] or 0
        avg_volume = queryset.aggregate(Avg('volume_m3'))['volume_m3__avg'] or 0
        
        source_breakdown = {}
        for source_type, _ in SludgeCollection.SOURCE_CHOICES:
            count = queryset.filter(source_type=source_type).count()
            if count > 0:
                source_breakdown[source_type] = count
        
        thirty_days_ago = timezone.now().date() - datetime.timedelta(days=30)
        recent = queryset.filter(collection_date__gte=thirty_days_ago).count()
        
        return Response({
            'total_manifests': total,
            'pending': pending,
            'completed': completed,
            'completion_rate': round((completed / total * 100) if total > 0 else 0, 2),
            'total_volume_m3': round(total_volume, 2),
            'average_volume_m3': round(avg_volume, 2),
            'by_source_type': source_breakdown,
            'recent_manifests_30d': recent,
        })


# --- USER VIEWSET ---

class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for viewing users (read-only for frontend dropdowns).
    """
    queryset = User.objects.all().order_by('username')
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated]
    
    @action(detail=False, methods=['get'])
    def me(self, request):
        """Get the current logged-in user's details"""
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def by_role(self, request):
        """Filter users by role (e.g., ?role=inspector)"""
        role = request.query_params.get('role', None)
        if role:
            users = self.get_queryset().filter(role=role)
        else:
            users = self.get_queryset()
        serializer = self.get_serializer(users, many=True)
        return Response(serializer.data)


# --- INSPECTION VIEWSET ---

class InspectionViewSet(viewsets.ModelViewSet):
    """
    ViewSet for Viewing and Editing Sewer Inspections.
    """
    queryset = Inspection.objects.all().order_by('-start_date')
    serializer_class = InspectionSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter inspections based on user role and query params"""
        queryset = super().get_queryset()
        user = self.request.user
        
        if user.role == 'inspector':
            queryset = queryset.filter(inspector=user)
        
        start_date = self.request.query_params.get('start_date', None)
        end_date = self.request.query_params.get('end_date', None)
        
        if start_date:
            queryset = queryset.filter(start_date__gte=start_date)
        if end_date:
            queryset = queryset.filter(end_date__lte=end_date)
            
        return queryset

    def perform_create(self, serializer):
        serializer.save(inspector=self.request.user)
    
    @action(detail=True, methods=['get'])
    def entries(self, request, pk=None):
        """Get all entries for a specific inspection"""
        inspection = self.get_object()
        entries = inspection.entries.all().order_by('date', 'section_identifier')
        from .serializers import InspectionEntrySerializer
        serializer = InspectionEntrySerializer(entries, many=True)
        return Response(serializer.data)
    
    @action(detail=True, methods=['post'])
    def add_entry(self, request, pk=None):
        """Add a new entry to an existing inspection"""
        inspection = self.get_object()
        from .serializers import InspectionEntrySerializer
        
        serializer = InspectionEntrySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(inspection=inspection)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    @action(detail=False, methods=['get'])
    def my_inspections(self, request):
        """Get inspections assigned to the current user"""
        inspections = self.get_queryset().filter(inspector=request.user)
        serializer = self.get_serializer(inspections, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def summary(self, request):
        """Get summary statistics for inspections"""
        queryset = self.get_queryset()
        total = queryset.count()
        pending = queryset.filter(end_date__isnull=True).count()
        completed = queryset.filter(end_date__isnull=False).count()
        
        return Response({
            'total': total,
            'pending': pending,
            'completed': completed,
        })


# --- TREATMENT LOG VIEWSET ---

class TreatmentLogViewSet(viewsets.ModelViewSet):
    """
    ViewSet for Viewing and Editing Treatment Logs.
    """
    queryset = TreatmentLog.objects.all().order_by('-report_date', '-created_at')
    serializer_class = TreatmentLogSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter treatment logs based on user role and query params"""
        queryset = super().get_queryset()
        user = self.request.user
        
        if user.role == 'operator':
            queryset = queryset.filter(operator=user)
        
        start_date = self.request.query_params.get('start_date', None)
        end_date = self.request.query_params.get('end_date', None)
        
        if start_date:
            queryset = queryset.filter(report_date__gte=start_date)
        if end_date:
            queryset = queryset.filter(report_date__lte=end_date)
        
        alert_only = self.request.query_params.get('alert_only', None)
        if alert_only and alert_only.lower() == 'true':
            queryset = queryset.filter(alert=True)
            
        return queryset

    def perform_create(self, serializer):
        serializer.save(operator=self.request.user)
    
    @action(detail=True, methods=['get'])
    def parameters(self, request, pk=None):
        """Get all parameters for a specific treatment log"""
        tlog = self.get_object()
        parameters = tlog.parameters.all().order_by('parameter')
        from .serializers import TreatmentParameterSerializer
        serializer = TreatmentParameterSerializer(parameters, many=True)
        return Response(serializer.data)
    
    @action(detail=True, methods=['post'])
    def add_parameter(self, request, pk=None):
        """Add a new parameter to an existing treatment log"""
        tlog = self.get_object()
        from .serializers import TreatmentParameterSerializer
        
        serializer = TreatmentParameterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(tlog=tlog)
            self._update_alert_status(tlog)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    @action(detail=False, methods=['get'])
    def alerts(self, request):
        """Get only treatment logs with active alerts"""
        alerts = self.get_queryset().filter(alert=True)
        serializer = self.get_serializer(alerts, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def my_logs(self, request):
        """Get treatment logs created by the current user"""
        logs = self.get_queryset().filter(operator=request.user)
        serializer = self.get_serializer(logs, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def summary(self, request):
        """Get summary statistics for treatment logs"""
        queryset = self.get_queryset()
        total = queryset.count()
        with_alerts = queryset.filter(alert=True).count()
        
        thirty_days_ago = timezone.now().date() - datetime.timedelta(days=30)
        recent_logs = queryset.filter(report_date__gte=thirty_days_ago)
        
        return Response({
            'total_logs': total,
            'logs_with_alerts': with_alerts,
            'alert_percentage': round((with_alerts / total * 100) if total > 0 else 0, 2),
            'recent_logs_count': recent_logs.count(),
        })
    
    def _update_alert_status(self, tlog):
        """Helper method to recalculate alert status for a treatment log"""
        has_alert = False
        for param in tlog.parameters.all():
            param_name = param.parameter.lower()
            effluent = param.effluent_value
            
            if effluent is None:
                continue
                
            if param_name == 'ph' and (effluent < 6.5 or effluent > 9.0):
                has_alert = True
            elif param_name in ['bod', 'cod'] and effluent > 30.0:
                has_alert = True
            elif param_name == 'tss' and effluent > 50.0:
                has_alert = True
            elif param_name == 'turbidity' and effluent > 5.0:
                has_alert = True
            elif param_name in ['chlorine', 'cl2'] and (effluent < 0.2 or effluent > 4.0):
                has_alert = True
        
        if tlog.alert != has_alert:
            tlog.alert = has_alert
            tlog.save()


# --- ATTACHMENT VIEWSET ---

class AttachmentViewSet(viewsets.ModelViewSet):
    """
    ViewSet for managing file attachments.
    """
    queryset = Attachment.objects.all().order_by('-uploaded_at')
    serializer_class = AttachmentSerializer
    permission_classes = [IsAuthenticated]
    parser_classes = [MultiPartParser, FormParser]

    def get_queryset(self):
        """Filter attachments by content type and object ID if provided"""
        queryset = super().get_queryset()
        
        content_type = self.request.query_params.get('content_type', None)
        object_id = self.request.query_params.get('object_id', None)
        
        if content_type:
            queryset = queryset.filter(content_type=content_type)
        if object_id:
            queryset = queryset.filter(object_id=object_id)
            
        return queryset

    def perform_create(self, serializer):
        serializer.save(uploaded_by=self.request.user)
    
    @action(detail=False, methods=['get'])
    def for_entity(self, request):
        """Get attachments for a specific entity (e.g., ?type=incident&id=5)"""
        content_type = request.query_params.get('type', None)
        object_id = request.query_params.get('id', None)
        
        if not content_type or not object_id:
            return Response(
                {'error': 'Both type and id parameters are required'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        attachments = self.get_queryset().filter(
            content_type=content_type,
            object_id=object_id
        )
        serializer = self.get_serializer(attachments, many=True)
        return Response(serializer.data)


# --- REPAIR VIEWSET ---

class RepairViewSet(viewsets.ModelViewSet):
    """
    ViewSet for managing repair completion certificates.
    """
    queryset = Repair.objects.all().order_by('-created_at')
    serializer_class = RepairSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter repairs based on user role and query params"""
        queryset = super().get_queryset()
        user = self.request.user
        
        if user.role == 'technician':
            queryset = queryset.filter(technician=user)
        
        incident_id = self.request.query_params.get('incident', None)
        if incident_id:
            queryset = queryset.filter(incident_id=incident_id)
        
        certified = self.request.query_params.get('certified', None)
        if certified is not None:
            if certified.lower() == 'true':
                queryset = queryset.filter(certified_at__isnull=False)
            elif certified.lower() == 'false':
                queryset = queryset.filter(certified_at__isnull=True)
                
        return queryset

    def perform_create(self, serializer):
        serializer.save(technician=self.request.user)

    @action(detail=True, methods=['patch'], permission_classes=[IsAuthenticated, IsSupervisor])
    def certify(self, request, pk=None):
        """
        Certify a repair with supervisor signature.
        """
        repair = self.get_object()
        
        if repair.certified_at:
            return Response(
                {'error': 'This repair has already been certified.'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        signature = request.FILES.get('supervisor_signature')
        
        if not signature:
            return Response(
                {'error': 'Supervisor signature is required to certify a repair.'}, 
                status=status.HTTP_400_BAD_REQUEST
            )
            
        repair.supervisor = request.user
        repair.supervisor_signature = signature
        repair.certified_at = timezone.now()
        repair.save()
        
        serializer = self.get_serializer(repair)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def uncertified(self, request):
        """Get all repairs that haven't been certified yet"""
        uncertified = self.get_queryset().filter(certified_at__isnull=True)
        serializer = self.get_serializer(uncertified, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def my_repairs(self, request):
        """Get repairs created by or assigned to the current user"""
        user = request.user
        repairs = self.get_queryset().filter(
            Q(technician=user) | Q(supervisor=user)
        ).distinct()
        serializer = self.get_serializer(repairs, many=True)
        return Response(serializer.data)


# --- INCIDENT VIEWSET ---

class IncidentViewSet(viewsets.ModelViewSet):
    """
    ViewSet for managing incidents.
    """
    queryset = Incident.objects.all().order_by('-reported_at', '-created_at')
    serializer_class = IncidentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter incidents based on query params"""
        queryset = super().get_queryset()
        
        status = self.request.query_params.get('status', None)
        if status:
            queryset = queryset.filter(status=status)
        
        assigned_to = self.request.query_params.get('assigned_to', None)
        if assigned_to:
            queryset = queryset.filter(assigned_to_id=assigned_to)
        
        from_date = self.request.query_params.get('from_date', None)
        to_date = self.request.query_params.get('to_date', None)
        
        if from_date:
            queryset = queryset.filter(reported_at__date__gte=from_date)
        if to_date:
            queryset = queryset.filter(reported_at__date__lte=to_date)
            
        return queryset

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)
    
    @action(detail=True, methods=['post'])
    def assign(self, request, pk=None):
        """Assign an incident to a user"""
        incident = self.get_object()
        user_id = request.data.get('user_id')
        
        if not user_id:
            return Response(
                {'error': 'user_id is required'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        try:
            user = User.objects.get(id=user_id)
            incident.assigned_to = user
            incident.save()
            serializer = self.get_serializer(incident)
            return Response(serializer.data)
        except User.DoesNotExist:
            return Response(
                {'error': 'User not found'},
                status=status.HTTP_404_NOT_FOUND
            )
    
    @action(detail=True, methods=['post'])
    def update_status(self, request, pk=None):
        """Update incident status"""
        incident = self.get_object()
        new_status = request.data.get('status')
        
        if not new_status:
            return Response(
                {'error': 'status is required'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        incident.status = new_status
        incident.save()
        serializer = self.get_serializer(incident)
        return Response(serializer.data)
    
    @action(detail=False, methods=['get'])
    def summary(self, request):
        """Get summary statistics for incidents"""
        queryset = self.get_queryset()
        total = queryset.count()
        by_status = {}
        
        for status_code, status_label in Incident.INCIDENT_STATUS:
            count = queryset.filter(status=status_code).count()
            if count > 0:
                by_status[status_code] = count
        
        return Response({
            'total': total,
            'by_status': by_status,
        })