# Generated by Django 6.0.2 on 2026-03-09 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-reported_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='Exhauster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(help_text='Unique registration number', max_length=50, unique=True)),
                ('owner', models.CharField(help_text='Owner name or company', max_length=200)),
                ('capacity_m3', models.DecimalField(decimal_places=2, help_text='Capacity in cubic meters', max_digits=6)),
                ('contact', models.CharField(blank=True, help_text='Contact information', max_length=100)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reg_no'],
                'indexes': [models.Index(fields=['reg_no'], name='core_exhaus_reg_no_49f40f_idx'), models.Index(fields=['status'], name='core_exhaus_status_3b5c2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section_identifier', models.CharField(help_text='Location or section being inspected', max_length=200)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, help_text='Length of section in meters', max_digits=8, null=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('minor', 'Minor Issues'), ('major', 'Major Defect')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('action', models.TextField(blank=True, help_text='Recommended or taken actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description_of_work', models.TextField()),
                ('materials_used', models.TextField(blank=True)),
                ('supervisor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='core.incident')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_supervisor', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('shift', models.CharField(blank=True, max_length=50)),
                ('operational_notes', models.TextField(blank=True)),
                ('alert', models.BooleanField(default=False, help_text='Flagged if parameters exceed regulatory thresholds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(help_text='e.g., Flow Rate, pH, BOD, TSS, etc.', max_length=100)),
                ('influent_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('influent_time', models.TimeField(blank=True, null=True)),
                ('effluent_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('effluent_time', models.TimeField(blank=True, null=True)),
                ('removal_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated efficiency: (influent - effluent)/influent * 100', max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.treatmentlog')),
            ],
            options={
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('content_type', models.CharField(help_text="e.g., 'incident', 'repair', 'inspection'", max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_8c2e5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('certify', 'Certify'), ('view', 'View')], max_length=50)),
                ('entity', models.CharField(help_text='e.g., incidents, repairs, treatmentlog, inspection', max_length=100)),
                ('entity_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Stores before/after values, IP address, user agent, etc.', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('pending', 'Pending Renewal')], default='valid', max_length=20)),
                ('fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhauster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core.exhauster')),
            ],
            options={
                'ordering': ['-end_date'],
                'indexes': [models.Index(fields=['exhauster', 'status'], name='core_licens_exhaust_3379b6_idx'), models.Index(fields=['license_no'], name='core_licens_license_73fb94_idx')],
            },
        ),
        migrations.CreateModel(
            name='SludgeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('source_type', models.CharField(choices=[('residential', 'Residential'), ('institutional', 'Institutional'), ('commercial', 'Commercial/Industrial')], max_length=50)),
                ('source_name', models.CharField(blank=True, help_text='Name of establishment/residence', max_length=255)),
                ('area_ward', models.CharField(blank=True, help_text='Location/Ward', max_length=200)),
                ('toilets_present', models.BooleanField(default=False, help_text='Whether toilets were present at source')),
                ('volume_m3', models.DecimalField(decimal_places=3, help_text='Volume collected in cubic meters', max_digits=8)),
                ('users', models.PositiveIntegerField(blank=True, help_text='Number of users served', null=True)),
                ('last_emptied', models.DateField(blank=True, help_text='Date of last emptying (if known)', null=True)),
                ('waste_description', models.TextField(blank=True, help_text='Description of waste characteristics')),
                ('receiving_notes', models.TextField(blank=True, help_text='Notes from receiving officer')),
                ('manifest_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhauster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.exhauster')),
                ('exhauster_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_driven', to=settings.AUTH_USER_MODEL)),
                ('receiving_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
                'indexes': [models.Index(fields=['collection_date'], name='core_sludge_collect_2ac97a_idx'), models.Index(fields=['manifest_status'], name='core_sludge_manifes_43d2df_idx'), models.Index(fields=['exhauster', 'collection_date'], name='core_sludge_exhaust_58c53c_idx')],
            },
        ),
    ]
