# Generated by Django 6.0.2 on 2026-04-05 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ensure_bootstrap_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ward', models.CharField(choices=[('kerugoya', 'Kerugoya'), ('kutus', 'Kutus'), ('sagana', 'Sagana')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_connection_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('applicant_name', models.CharField(max_length=255)),
                ('id_no', models.CharField(help_text='ID or Passport Number', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('institutional', 'Institutional')], default='residential', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.connectionreport')),
            ],
        ),
    ]
