# Generated by Django 6.0.2 on 2026-04-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_connectionreport_connectionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superintendent', 'Superintendent (Grade 3)'), ('supervisor', 'Supervisor (Grade 4)'), ('lab_tech', 'Lab Technologist (Grade 4)'), ('operator', 'Operator (Grade 5)'), ('attendant', 'Attendant/Plumber (Grade 6)'), ('admin', 'System Admin')], default='attendant', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('attendants', models.ManyToManyField(related_name='flow_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM'), ('12:00', '12:00 PM'), ('15:00', '3:00 PM'), ('18:00', '6:00 PM')], max_length=10)),
                ('meter_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meter_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.dailyflowrecord')),
            ],
        ),
        migrations.CreateModel(
            name='InletWorksDailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('raking_t1', models.BooleanField(default=False)),
                ('raking_t2', models.BooleanField(default=False)),
                ('raking_t3', models.BooleanField(default=False)),
                ('screenings_burial', models.BooleanField(default=False)),
                ('grit_scooping', models.BooleanField(default=False)),
                ('grit_burial', models.BooleanField(default=False)),
                ('abnormalities', models.TextField(blank=True)),
                ('operator_signature', models.ImageField(blank=True, null=True, upload_to='signatures/inlet/')),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inlet_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLinePatrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('drainage_area', models.CharField(max_length=200)),
                ('sewer_line_ref', models.CharField(max_length=100)),
                ('abnormality_observed', models.CharField(choices=[('none', 'None'), ('erosion', 'Erosion along lines'), ('missing_cover', 'Broken/Missing Manhole Cover'), ('blockage', 'Blockage'), ('overflow', 'Overflow/Spillage'), ('other', 'Other (Specify in remarks)')], default='none', max_length=50)),
                ('abnormality_details', models.TextField(blank=True, help_text="Specify if 'Other' or add details")),
                ('new_mother_accounts', models.PositiveIntegerField(default=0)),
                ('new_child_accounts', models.PositiveIntegerField(default=0)),
                ('corrective_action_taken', models.TextField(blank=True)),
                ('further_action_required', models.TextField(blank=True)),
                ('supervisor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/patrols/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrols', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
