# Generated by Django 6.0.2 on 2026-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role_dailyflowrecord_flowreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('blockage', 'Blockage'), ('burst', 'Burst Pipe'), ('spillage', 'Sewer Spillage'), ('odor', 'Foul Odor'), ('missing_cover', 'Missing Manhole Cover'), ('illegal_connection', 'Illegal Connection'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('high', 'High (Emergency/Critical)'), ('medium', 'Medium (Urgent/Operational)'), ('low', 'Low (Routine/Minor)')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(help_text='Additional details about the incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_text',
            field=models.CharField(blank=True, help_text='Landmarks or physical description', max_length=255),
        ),
    ]
