# Generated by Django 6.0.2 on 2026-04-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_material_remove_repair_materials_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequisition',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialrequisition',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='description_of_work',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='materials_notes',
        ),
        migrations.AddField(
            model_name='incident',
            name='assisting_crew',
            field=models.CharField(blank=True, help_text='Names of other technicians assisting the lead', max_length=255),
        ),
        migrations.AddField(
            model_name='repair',
            name='materials_used',
            field=models.TextField(blank=True, help_text='Manually list materials used (e.g., 2 PVC pipes, 1 bag cement)'),
        ),
        migrations.AddField(
            model_name='repair',
            name='repair_type',
            field=models.CharField(choices=[('rodding', 'Rodding / Unblocking'), ('jetting', 'High-Pressure Jetting'), ('pipe_replacement', 'Pipe Replacement'), ('manhole_repair', 'Manhole / Cover Repair'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='repair',
            name='scope_of_work',
            field=models.TextField(default='Legacy repair scope not provided', help_text='Describe the exact work performed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold_materials', 'On Hold - Awaiting Materials'), ('on_hold_equipment', 'On Hold - Requires Equipment/Excavator'), ('pending_certification', 'Pending Certification'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=30),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialRequisition',
        ),
    ]
