# Generated by Django 6.0.2 on 2026-05-13 18:07

import django.db.models.deletion
from django.db import migrations, models


def copy_weekly_patrol_data(apps, schema_editor):
    WeeklyLinePatrol = apps.get_model('core', 'WeeklyLinePatrol')
    SewerLineSection = apps.get_model('core', 'SewerLineSection')
    PatrolRow = apps.get_model('core', 'PatrolRow')

    for patrol in WeeklyLinePatrol.objects.all().order_by('id'):
        if not patrol.week_number:
            patrol.week_number = patrol.date.isocalendar().week
            patrol.save(update_fields=['week_number'])

        section_code = getattr(patrol, 'sewer_line_ref', '') or f'LEGACY-{patrol.id}'
        section, _ = SewerLineSection.objects.get_or_create(
            code=section_code,
            defaults={'is_confirmed': False},
        )

        PatrolRow.objects.create(
            weekly_patrol=patrol,
            time=getattr(patrol, 'time'),
            sewer_line_section=section,
            sewer_line_ref_text=getattr(patrol, 'sewer_line_ref', '') or section.code,
            abnormality_observed=getattr(patrol, 'abnormality_observed', 'none'),
            abnormality_details=getattr(patrol, 'abnormality_details', ''),
            new_mother_connections=getattr(patrol, 'new_mother_accounts', 0),
            new_child_connections=getattr(patrol, 'new_child_accounts', 0),
            immediate_action_taken=getattr(patrol, 'corrective_action_taken', ''),
            further_action_required=getattr(patrol, 'further_action_required', ''),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_incident_source_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewerLineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='weeklylinepatrol',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PatrolRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('sewer_line_ref_text', models.CharField(max_length=100)),
                ('abnormality_observed', models.CharField(choices=[('none', 'None'), ('erosion', 'Erosion along lines'), ('missing_cover', 'Broken/Missing Manhole Cover'), ('blockage', 'Blockage'), ('overflow', 'Overflow/Spillage'), ('other', 'Other (Specify in remarks)')], default='none', max_length=50)),
                ('abnormality_details', models.TextField(blank=True, help_text="Specify if 'Other' or add details")),
                ('new_mother_connections', models.PositiveIntegerField(default=0)),
                ('new_child_connections', models.PositiveIntegerField(default=0)),
                ('immediate_action_taken', models.TextField(blank=True)),
                ('further_action_required', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_rows', to='core.incident')),
                ('weekly_patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.weeklylinepatrol')),
                ('sewer_line_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrol_rows', to='core.sewerlinesection')),
            ],
            options={
                'ordering': ['time', 'id'],
            },
        ),
        migrations.RunPython(copy_weekly_patrol_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='abnormality_details',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='abnormality_observed',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='corrective_action_taken',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='further_action_required',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='new_child_accounts',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='new_mother_accounts',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='sewer_line_ref',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='supervisor_signature',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='time',
        ),
    ]
