# Generated by Django 6.0.2 on 2026-05-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patrol_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklylinepatrol',
            options={'ordering': ['-date']},
        ),
    ]
