# Generated by Django 6.0.2 on 2026-05-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sludge_workflow_exhausterlicense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exhausterlicense',
            new_name='core_exhaus_exhaust_6a4f45_idx',
            old_name='core_licens_exhaust_3379b6_idx',
        ),
        migrations.RenameIndex(
            model_name='exhausterlicense',
            new_name='core_exhaus_license_9ddbd2_idx',
            old_name='core_licens_license_73fb94_idx',
        ),
    ]
