# Generated by Django 6.0.2 on 2026-05-13 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_incident_repair_statemachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(unique=True)),
                ('inflow_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inflow_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inflow_tss', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — D', max_digits=8, null=True)),
                ('inflow_bod', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — 2W', max_digits=8, null=True)),
                ('inflow_cod', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — W', max_digits=8, null=True)),
                ('inflow_tn', models.DecimalField(blank=True, decimal_places=2, help_text='Total Nitrogen mg/L — M', max_digits=8, null=True)),
                ('inflow_tp', models.DecimalField(blank=True, decimal_places=2, help_text='Total Phosphorus mg/L — M', max_digits=8, null=True)),
                ('inflow_fc', models.DecimalField(blank=True, decimal_places=2, help_text='Fecal Coliforms CFU/100mL — W', max_digits=12, null=True)),
                ('effluent_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effluent_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effluent_tss', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — D', max_digits=8, null=True)),
                ('effluent_bod', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — 2W', max_digits=8, null=True)),
                ('effluent_cod', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — W', max_digits=8, null=True)),
                ('effluent_tn', models.DecimalField(blank=True, decimal_places=2, help_text='Total Nitrogen mg/L — M', max_digits=8, null=True)),
                ('effluent_tp', models.DecimalField(blank=True, decimal_places=2, help_text='Total Phosphorus mg/L — M', max_digits=8, null=True)),
                ('effluent_fc', models.DecimalField(blank=True, decimal_places=2, help_text='Fecal Coliforms CFU/100mL — W', max_digits=12, null=True)),
                ('effluent_turbidity', models.DecimalField(blank=True, decimal_places=2, help_text='NTU — D', max_digits=8, null=True)),
                ('effluent_chlorine', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L — D', max_digits=6, null=True)),
                ('effluent_do', models.DecimalField(blank=True, decimal_places=2, help_text='Dissolved Oxygen mg/L — D', max_digits=6, null=True)),
                ('volume_treated_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sludge_volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified')], default='submitted', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['record_date'], name='core_dailyl_record__b8ae5f_idx'), models.Index(fields=['status'], name='core_dailyl_status_15497e_idx')],
            },
        ),
    ]
