# Generated by Django 6.0.2 on 2026-05-13 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_monthlysummary_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PondYearlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pond_yearly_tasks', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yearly_tasks', to='core.treatmentpond')),
            ],
            options={
                'ordering': ['year', 'pond__code', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PondDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('do_level', models.DecimalField(blank=True, decimal_places=2, help_text='Dissolved Oxygen mg/L', max_digits=6, null=True)),
                ('surface_scum', models.BooleanField(default=False)),
                ('odour_complaint', models.BooleanField(default=False)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('cosigned_op', 'Co-signed by Operator'), ('verified', 'Verified by Supervisor')], default='submitted', max_length=20)),
                ('cosigned_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cosigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pond_logs_cosigned', to=settings.AUTH_USER_MODEL)),
                ('incident_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pond_logs', to='core.incident')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pond_logs_submitted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pond_logs_verified', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='core.treatmentpond')),
            ],
            options={
                'ordering': ['-log_date', 'pond__code'],
                'indexes': [models.Index(fields=['log_date'], name='core_pondda_log_dat_37e0b6_idx'), models.Index(fields=['status'], name='core_pondda_status_57f7cd_idx')],
                'unique_together': {('pond', 'log_date')},
            },
        ),
    ]
