# Generated by Django 6.0.2 on 2026-05-13 22:38

from django.db import migrations, models


def backfill_application_ward(apps, schema_editor):
    ConnectionApplication = apps.get_model('core', 'ConnectionApplication')
    for app in ConnectionApplication.objects.select_related('report').filter(ward=''):
        if app.report_id and hasattr(app.report, 'ward'):
            app.ward = app.report.ward or ''
            app.save(update_fields=['ward'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_pond_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='ward',
            field=models.CharField(blank=True, choices=[('kerugoya', 'Kerugoya'), ('kutus', 'Kutus'), ('sagana', 'Sagana')], max_length=50),
        ),
        migrations.RunPython(backfill_application_ward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='connectionreport',
            name='ward',
        ),
    ]
