# Generated by Django 6.0.2 on 2026-05-17 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_sewer_line_officer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='assignment_instructions',
            field=models.TextField(blank=True, help_text='Supervisor notes for the assigned attendant', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='certified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_incidents', to='core.incident'),
        ),
        migrations.CreateModel(
            name='SewerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_point', models.CharField(blank=True, max_length=255)),
                ('end_point', models.CharField(blank=True, max_length=255)),
                ('pipe_material', models.CharField(blank=True, max_length=100)),
                ('diameter_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewer_lines', to='core.zone')),
            ],
            options={
                'ordering': ['reference_code'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.zone'),
        ),
    ]
