# Generated by Django 6.0.2 on 2026-05-18 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_notification_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sewerline',
            options={'ordering': ['zone', 'reference_code']},
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sewerline',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sewerline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_zones',
            field=models.ManyToManyField(blank=True, help_text='Zones assigned to this line attendant', related_name='assigned_attendants', to='core.zone'),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number for notifications", max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assignment_instructions',
            field=models.TextField(blank=True, help_text='Additional notes from supervisor during assignment'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='certified_at',
            field=models.DateTimeField(blank=True, help_text='When the repair was certified', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='certified_by',
            field=models.ForeignKey(blank=True, help_text='Supervisor who certified the repair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the incident repair was completed', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='related_incident',
            field=models.ForeignKey(blank=True, help_text='Link to a previous incident at the same or related location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_incidents', to='core.incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone/drainage area where the incident occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.zone'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('incident_critical', 'Critical Incident'), ('patrol_submitted', 'Patrol Log Submitted'), ('approval', 'Approval Request'), ('system', 'System Alert')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='sewerline',
            name='diameter_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Pipe diameter in millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='sewerline',
            name='end_point',
            field=models.CharField(blank=True, help_text='Ending manhole or location', max_length=255),
        ),
        migrations.AlterField(
            model_name='sewerline',
            name='pipe_material',
            field=models.CharField(blank=True, choices=[('pvc', 'PVC'), ('ac', 'Asbestos Cement (AC)'), ('hdpe', 'HDPE'), ('ductile_iron', 'Ductile Iron'), ('concrete', 'Concrete'), ('earthenware', 'Earthenware'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sewerline',
            name='reference_code',
            field=models.CharField(help_text='e.g., SL-104', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sewerline',
            name='start_point',
            field=models.CharField(blank=True, help_text='Starting manhole or location', max_length=255),
        ),
        migrations.AddIndex(
            model_name='sewerline',
            index=models.Index(fields=['zone', 'is_active'], name='core_sewerl_zone_id_725fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='sewerline',
            index=models.Index(fields=['reference_code'], name='core_sewerl_referen_4b56d0_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_active'], name='core_zone_is_acti_bad536_idx'),
        ),
    ]
