# Generated by Django 6.0.2 on 2026-05-18 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_notification_and_sewer_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolrow',
            name='new_child_connections',
        ),
        migrations.RemoveField(
            model_name='patrolrow',
            name='new_mother_connections',
        ),
        migrations.RemoveField(
            model_name='weeklylinepatrol',
            name='drainage_area',
        ),
        migrations.AddField(
            model_name='patrolrow',
            name='new_branch_connections',
            field=models.PositiveIntegerField(default=0, help_text='New branch connection found (Section 5.2)'),
        ),
        migrations.AddField(
            model_name='patrolrow',
            name='new_main_connections',
            field=models.PositiveIntegerField(default=0, help_text='New main connection found (Section 5.2)'),
        ),
        migrations.AddField(
            model_name='patrolrow',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo attachment per row (Section 5.6)', null=True, upload_to='patrol_photos/'),
        ),
        migrations.AddField(
            model_name='weeklylinepatrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weeklylinepatrol',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone/drainage area for this patrol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrols', to='core.zone'),
        ),
        migrations.AlterField(
            model_name='patrolrow',
            name='abnormality_details',
            field=models.TextField(blank=True, help_text="Specify if 'Other' or add details (Section 5.4)"),
        ),
        migrations.AlterField(
            model_name='patrolrow',
            name='further_action_required',
            field=models.TextField(blank=True, help_text='Actions needed (Section 5.4 - hidden if empty)'),
        ),
        migrations.AlterField(
            model_name='weeklylinepatrol',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='submitted', help_text='draft=not notified, submitted=supervisor notified, verified=supervisor reviewed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='weeklylinepatrol',
            index=models.Index(fields=['zone', 'status'], name='core_weekly_zone_id_4bddcf_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklylinepatrol',
            index=models.Index(fields=['attendant', '-date'], name='core_weekly_attenda_2375e3_idx'),
        ),
    ]
