# Generated by Django 6.0.2 on 2026-05-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_role_portal_workflow_refinement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labcomplianceflag',
            new_name='core_labcom_severit_c62bfe_idx',
            old_name='core_labcom_severit_7026e9_idx',
        ),
        migrations.RenameIndex(
            model_name='labcomplianceflag',
            new_name='core_labcom_paramet_aaf102_idx',
            old_name='core_labcom_paramet_d649dd_idx',
        ),
        migrations.AddField(
            model_name='dailylabrecord',
            name='correction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inletworksdailytask',
            name='correction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylabrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_operator', 'Pending Operator Co-sign'), ('returned', 'Returned for Correction'), ('fully_signed', 'Fully Signed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='inletworksdailytask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_operator', 'Pending Operator Co-sign'), ('returned', 'Returned for Correction'), ('fully_signed', 'Fully Signed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ponddailylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_second_sign', 'Pending Second Sign'), ('pending_supervisor', 'Pending Supervisor Sign'), ('fully_signed', 'Fully Signed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sludgecollection',
            name='manifest_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylinepatrol',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', help_text='draft=not notified, submitted=supervisor notified, verified=supervisor reviewed', max_length=20),
        ),
    ]
