# Generated by Django 6.0.2 on 2026-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_core_labcom_severit_7026e9_idx_core_labcom_severit_c62bfe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inletworksdailytask',
            name='grit_burial_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inletworksdailytask',
            name='grit_scooping_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inletworksdailytask',
            name='raking_t1_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inletworksdailytask',
            name='raking_t2_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inletworksdailytask',
            name='raking_t3_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inletworksdailytask',
            name='screenings_burial_reason',
            field=models.TextField(blank=True),
        ),
    ]
