# Generated by Django 6.0.2 on 2026-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_inletworksdailytask_grit_burial_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpond',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice_weekly', 'Twice Weekly (Mon/Wed/Fri)'), ('weekly', 'Weekly (Friday)'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
