# Generated by Django 6.0.2 on 2026-05-23 20:26

import django.db.models.deletion
import datetime
from django.conf import settings
from django.db import migrations, models


def migrate_repairs_to_attempts(apps, schema_editor):
    Incident = apps.get_model('core', 'Incident')
    Repair = apps.get_model('core', 'Repair')
    RepairAttempt = apps.get_model('core', 'RepairAttempt')

    for incident in Incident.objects.all().iterator():
        Incident.objects.filter(pk=incident.pk).update(
            system_suggested_severity=incident.severity,
            final_severity=incident.severity,
        )

    for repair in Repair.objects.all().iterator():
        incident_id = repair.incident_id
        if not incident_id:
            continue
        exists = RepairAttempt.objects.filter(incident_id=incident_id, attempt_number=1).exists()
        if exists:
            continue
        RepairAttempt.objects.create(
            incident_id=incident_id,
            attempt_number=1,
            work_performed=repair.scope_of_work or '',
            materials_used=repair.materials_used or '',
            attendant_id=repair.technician_id,
            submitted_at=repair.completed_at or repair.updated_at or repair.created_at,
        )


def reverse_migrate_attempts_to_repairs(apps, schema_editor):
    Repair = apps.get_model('core', 'Repair')
    RepairAttempt = apps.get_model('core', 'RepairAttempt')

    for attempt in RepairAttempt.objects.filter(attempt_number=1).iterator():
        if Repair.objects.filter(incident_id=attempt.incident_id).exists():
            continue
        submitted_at = attempt.submitted_at
        Repair.objects.create(
            incident_id=attempt.incident_id,
            completion_date=submitted_at.date() if submitted_at else datetime.date.today(),
            location=attempt.incident.location_text if attempt.incident_id else '',
            scope_of_work=attempt.work_performed,
            materials_used=attempt.materials_used,
            technician_id=attempt.attendant_id,
            repair_type='other',
            status='completed',
            completed_at=submitted_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_portal_refinement_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='final_severity',
            field=models.CharField(choices=[('critical', 'Critical (Emergency)'), ('high', 'High (Emergency/Critical)'), ('medium', 'Medium (Urgent/Operational)'), ('low', 'Low (Routine/Minor)')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='revision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='system_suggested_severity',
            field=models.CharField(choices=[('critical', 'Critical (Emergency)'), ('high', 'High (Emergency/Critical)'), ('medium', 'Medium (Urgent/Operational)'), ('low', 'Low (Routine/Minor)')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='patrolrow',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrolrow',
            name='sewer_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_rows', to='core.sewerline'),
        ),
        migrations.AddField(
            model_name='patrolrow',
            name='sewer_line_ref_manual',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sewerline',
            name='patrol_frequency_per_month',
            field=models.PositiveIntegerField(default=4, help_text='Expected number of patrol submissions per month for this line'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Format: KCW-YYYY-NNN', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical (Emergency)'), ('high', 'High (Emergency/Critical)'), ('medium', 'Medium (Urgent/Operational)'), ('low', 'Low (Routine/Minor)')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('revision_required', 'Revision Required'), ('on_hold_materials', 'On Hold - Awaiting Materials'), ('on_hold_equipment', 'On Hold - Requires Equipment/Excavator'), ('pending_certification', 'Pending Certification'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('deferred', 'Deferred')], default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='FieldMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('supervisor_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'stp_superintendent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_field_reports', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'line_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('month', 'year', 'supervisor')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(max_length=200)),
                ('connection_status', models.CharField(choices=[('unconnected', 'Unconnected'), ('applied', 'Application Submitted'), ('approved', 'Approved'), ('connected', 'Connected'), ('rejected', 'Rejected')], default='unconnected', max_length=20)),
                ('connection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nearest_sewer_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sewerline')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='RepairAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('work_performed', models.TextField()),
                ('materials_used', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_attempts', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_attempts', to='core.incident')),
            ],
            options={
                'ordering': ['attempt_number'],
                'unique_together': {('incident', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField(auto_now_add=True)),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('attendant', models.ForeignKey(limit_choices_to={'role': 'line_attendant'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'line_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_attendants', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone')),
            ],
        ),
        migrations.RunPython(migrate_repairs_to_attempts, reverse_migrate_attempts_to_repairs),
        migrations.DeleteModel(
            name='Repair',
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', True)), fields=('attendant',), name='unique_active_membership_per_attendant'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('supervisor', 'attendant', 'assigned_to')},
        ),
    ]
